### ISSUE TITLE
crash on dedicated Server

### ISSUE THREAD

**Issue by ZEROX7** [TechnicalitiesMC/SuperCircuitMaker#4]
hey there heres a crash log on my dedicated server
[crash-2021-12-26_19.42.23-fml.txt](https://github.com/TechnicalitiesMC/SuperCircuitMaker/files/7777396/crash-2021-12-26_19.42.23-fml.txt)

**Comment by amadornes** [comment]
Thanks for reporting this! Just patched it in 225c975697723e88c322dae1e761e9adc91153f9.  
I hadn't had a chance to test it on a dedicated server, which is why it was marked as alpha on CurseForge.  

v0.1.0 is now live with the fix:  
**CurseForge:** https://mc-mods.cf/super-circuit-maker/files/3581169  
**GitHub:** https://github.com/TechnicalitiesMC/SuperCircuitMaker/releases/tag/v0.1.0
