### ISSUE TITLE
[question] blueprints and missing stuff

### ISSUE THREAD

**Issue by Kiryonn** [TechnicalitiesMC/SuperCircuitMaker#7]
hi. I'm curently playing with the 1.18.1 version. I watched the videos introducing the mod and installed it cause i love playing with logical stuff. I imediatelly started to try it in a creative world, tho quickly noticed the missing of some components introduced in the videos. For example, there was no blueprint, no multimeter, other predefined circuits, the screwdriver wasn't able to make the circuit inputs/outputs appear (i'm talking about the interface where you can choose redstone + bundle or bundle alone)

i was wondering if it was missing because it was not implemented in the 1.18 version yet or if it was a bug on my side, or dependencies that i didn't installed.

Also i was wondering if you will port to fabric, since the porting from a version to another is easier on fabric from what i've heard.

**Comment by amadornes** [comment]
SCM 2 is still in a pretty early state, so not everything from the original is implemented, and there are some changes to certain parts of the mod. Pretty much everything you know from the original is coming back in one form or another, and of course there'll be new content as well, but it's going to take a while to get it all added and tested.

Some features like analog operators are staying the same, some like circuit-in-circuit are changing entirely, and others like blueprints and the multimeter are being tweaked.

---

As of right now there's no port to Fabric planned. As far as I'm aware the only "advantage" Fabric has when it comes to porting is that it's out sooner than Forge, but that seems to be changing going forward, with Forge aiming to have something out for modders to play around with on the day the new version of the game comes out.

I might consider it down the line if I get a streamlined workspace for it and my other mods set up, because at the moment working on a mod for both platforms requires 3 projects per mod, and with my current plans I'd end up with over 30 projects in my dev environment, which is rather unmanageable.

Right now my focus is designing and adding content to this and my other unreleased projects, so I don't want to have to be constantly fighting two mod loaders instead of just one.

**Comment by dkranke** [comment]
Hello, SCM 2 (the 1.18.1 version) is still in development, therefore still missing a couple of features.
The video you've seen most likely is from SCM 1 (1.10.2)
In the current version (beta 0.1.3) only digital components and and simple wires are implemented.

According to the Discord bundled wires are next, then analog components.
Blueprints are also planned, but the format in which circuits are going to be encoded still needs to be decided.

Colored wires are already implemented, just not accessible as the color palette item is still missing.
I don't know if you later will be able to hide circuits or if that is one of the new ASICs which will replace the nested circuits.

**Comment by Kiryonn** [comment]
Thanks you for your reply. I don't mind not having this mod on fabric, as long as i can play around with it i'm happy. I do understand the hardship coming from having to switch from one technology to another with a bunch of project. Thank you for your work, i will be waiting for your updates :)

**Comment by XFactHD** [comment]
> Colored wires are already implemented, just not accessible as the color palette item is still missing.

Colored wires can be used already, you can color the wires with normal dyes at the moment.

**Comment by SilverSCode** [comment]
I'm looking forward to the next update of this mod
