### ISSUE TITLE
Colored wires don't separate automatically

### ISSUE THREAD

**Issue by XFactHD** [TechnicalitiesMC/SuperCircuitMaker#8]
Colored redstone wires don't automatically separate when a color is applied to them, which makes them a lot less useful.
![2022-01-11_01 14 52](https://user-images.githubusercontent.com/11262040/148859603-5c05a9e7-6a4d-4ff1-af5a-cb19f4fe350b.png)

I can't remember if this was a thing in SCM 1 or not but it would be cool to have nontheless.

Forge: 1.18.1-39.0.8
SCM: 0.1.3

**Comment by amadornes** [comment]
In SCM 1 you used to have the palette, which isn't implemented yet.  
If I recall correctly, they wouldn't disconnect when applying a color to an existing wire, but if you had the palette in your off-hand while placing them, then they didn't connect.

I'll keep this issue open until that's added back, I suppose.

**Comment by amadornes** [comment]
The palette is in now, and wires placed while it's in the offhand will be automatically colored and only connect to wires of the same color. I've decided that automatically connecting wires when recoloring them won't be added because it has a good chance of causing issues when accidentally recoloring a wire, and there's use cases for having multiple separate wires of the same color next to each other.
